// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ViJFcrNmm0lIkmJttyWqfT_md4mtqi0',
    appId: '1:539805867738:web:43ec2ffb4e6925e2280fe3',
    messagingSenderId: '539805867738',
    projectId: 'chatgpt-app-9337b',
    authDomain: 'chatgpt-app-9337b.firebaseapp.com',
    storageBucket: 'chatgpt-app-9337b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ptu9flMdwkVvYKtAMsdIu08cv7XQCZA',
    appId: '1:539805867738:android:cb9ec50562f99195280fe3',
    messagingSenderId: '539805867738',
    projectId: 'chatgpt-app-9337b',
    storageBucket: 'chatgpt-app-9337b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdr_NS3AMDPaBQV9JW7uJiV3NZJzUFd08',
    appId: '1:539805867738:ios:400b633c659ed235280fe3',
    messagingSenderId: '539805867738',
    projectId: 'chatgpt-app-9337b',
    storageBucket: 'chatgpt-app-9337b.appspot.com',
    iosClientId: '539805867738-hm346vvfr75426v6a780s2vl21qeu0qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdr_NS3AMDPaBQV9JW7uJiV3NZJzUFd08',
    appId: '1:539805867738:ios:da1c6e13cc838691280fe3',
    messagingSenderId: '539805867738',
    projectId: 'chatgpt-app-9337b',
    storageBucket: 'chatgpt-app-9337b.appspot.com',
    iosClientId: '539805867738-ka8mh9na5q24i4l0pqc6cj9er3ddq38t.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatGpt.RunnerTests',
  );
}
